spring.application.name=api-padre

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}

resend.api-key=${RESEND_API_KEY}
resend.from-email=BarrioApp <onboarding@barrioapp.click>

flow.api-key=${FLOW_API_KEY}
flow.secret-key=${FLOW_SECRET_KEY}
flow.api-url=${FLOW_API_URL:https://sandbox.flow.cl/api}
flow.url-confirmation=${FLOW_URL_CONFIRMATION}
flow.url-return=${FLOW_URL_RETURN}